# Generated by Django 5.0.1 on 2025-12-29 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='인증 여부'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='닉네임'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='party',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='소속 정당'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reputation',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='평판 점수'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('citizen', '시민'), ('politician', '정치인'), ('admin', '관리자')], db_index=True, default='citizen', max_length=20, verbose_name='역할'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_verified'], name='users_is_veri_63cd6e_idx'),
        ),
    ]
