# Generated by Django 5.0.1 on 2025-12-29 15:53

from django.db import migrations


def populate_nicknames(apps, schema_editor):
    """기존 유저들의 nickname 자동 생성"""
    CustomUser = apps.get_model('users', 'CustomUser')

    for user in CustomUser.objects.all():
        if not user.nickname:  # nickname이 비어있는 경우만 처리
            if user.first_name and user.last_name:
                # 한국식 이름: 성 + 이름
                user.nickname = f"{user.last_name}{user.first_name}"
            else:
                # 이메일 앞부분을 nickname으로 사용
                user.nickname = user.email.split('@')[0][:50]
            user.save(update_fields=['nickname'])


def reverse_populate(apps, schema_editor):
    """Rollback: nickname을 빈 문자열로 초기화"""
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.update(nickname='')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_verified_customuser_nickname_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_nicknames, reverse_populate),
    ]
