# Generated by Django 5.0.1 on 2025-12-29 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0007_area_leader'),
        ('users', '0003_populate_user_nicknames'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='area',
            field=models.ForeignKey(blank=True, help_text='사용자가 거주하거나 담당하는 행정동', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='grievances.area', verbose_name='거주/담당 지역'),
        ),
    ]
