# Generated by Django 5.0.1 on 2025-12-24 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grievances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='grievanceimage',
            name='grievance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='grievances.grievance', verbose_name='민원'),
        ),
        migrations.AddField(
            model_name='like',
            name='grievance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='grievances.grievance', verbose_name='민원'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['-created_at'], name='grievances_created_311849_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['status'], name='grievances_status_aee5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['user', '-created_at'], name='grievances_user_id_859914_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'grievance'], name='likes_user_id_243967_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['grievance', '-created_at'], name='likes_grievan_e9efca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'grievance')},
        ),
    ]
