# Generated by Django 5.0.1 on 2025-12-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='category',
            field=models.CharField(choices=[('traffic', '교통/주차'), ('env', '환경/위생'), ('safety', '안전/치안'), ('facility', '공원/시설'), ('animal', '동물'), ('admin', '일반행정'), ('etc', '기타')], db_index=True, default='etc', max_length=20, verbose_name='카테고리'),
        ),
    ]
