# Generated by Django 5.0.1 on 2025-12-29 15:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0003_add_category_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceSecret',
            fields=[
                ('grievance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='secret', serialize=False, to='grievances.grievance', verbose_name='민원')),
                ('password_hash', models.CharField(help_text='평문 저장 금지 - 해시만 저장', max_length=255, verbose_name='패스워드 해시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '비공개 민원 패스워드',
                'verbose_name_plural': '비공개 민원 패스워드',
                'db_table': 'grievance_secrets',
            },
        ),
        migrations.AddField(
            model_name='grievance',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='민원 처리 완료 시각', null=True, verbose_name='완료 시각'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='visibility',
            field=models.CharField(choices=[('public', '공개'), ('private', '비공개')], db_index=True, default='public', max_length=20, verbose_name='공개 범위'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='행정동 이름')),
                ('center_point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='중심 좌표')),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='경계선')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '행정동',
                'verbose_name_plural': '행정동',
                'db_table': 'areas',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='areas_name_a940ef_idx')],
            },
        ),
        migrations.AddField(
            model_name='grievance',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grievances', to='grievances.area', verbose_name='발생 지역'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['visibility'], name='grievances_visibil_7b1a79_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['area', '-created_at'], name='grievances_area_id_aa4ce0_idx'),
        ),
    ]
