# Generated by Django 5.0.1 on 2025-12-29 15:53

from django.db import migrations
from django.contrib.gis.geos import Point


def populate_seoul_areas(apps, schema_editor):
    """서울 25개 구 + 미지정 구역 생성"""
    Area = apps.get_model('grievances', 'Area')

    seoul_districts = [
        {'name': '강남구', 'lng': 127.0495556, 'lat': 37.5172363},
        {'name': '강동구', 'lng': 127.1237708, 'lat': 37.5301251},
        {'name': '강북구', 'lng': 127.0256158, 'lat': 37.6398055},
        {'name': '강서구', 'lng': 126.8495556, 'lat': 37.5509451},
        {'name': '관악구', 'lng': 126.9516157, 'lat': 37.4784012},
        {'name': '광진구', 'lng': 127.0821667, 'lat': 37.5384843},
        {'name': '구로구', 'lng': 126.8874779, 'lat': 37.4954145},
        {'name': '금천구', 'lng': 126.8955449, 'lat': 37.4568642},
        {'name': '노원구', 'lng': 127.0561732, 'lat': 37.6542503},
        {'name': '도봉구', 'lng': 127.0471511, 'lat': 37.6688476},
        {'name': '동대문구', 'lng': 127.0396071, 'lat': 37.5744148},
        {'name': '동작구', 'lng': 126.9395279, 'lat': 37.5124229},
        {'name': '마포구', 'lng': 126.9025742, 'lat': 37.5662952},
        {'name': '서대문구', 'lng': 126.9361789, 'lat': 37.5791056},
        {'name': '서초구', 'lng': 127.0325477, 'lat': 37.4836966},
        {'name': '성동구', 'lng': 127.0369755, 'lat': 37.5633518},
        {'name': '성북구', 'lng': 127.0167291, 'lat': 37.5893795},
        {'name': '송파구', 'lng': 127.1052133, 'lat': 37.5145437},
        {'name': '양천구', 'lng': 126.8664073, 'lat': 37.5169558},
        {'name': '영등포구', 'lng': 126.8962862, 'lat': 37.5263932},
        {'name': '용산구', 'lng': 126.9644767, 'lat': 37.5323242},
        {'name': '은평구', 'lng': 126.9291403, 'lat': 37.6026783},
        {'name': '종로구', 'lng': 126.9791007, 'lat': 37.5730484},
        {'name': '중구', 'lng': 126.9975972, 'lat': 37.5636907},
        {'name': '중랑구', 'lng': 127.0925069, 'lat': 37.6063243},
        # 기본 fallback 구역
        {'name': '미지정', 'lng': 126.9780, 'lat': 37.5665},  # Seoul City Hall
    ]

    for district in seoul_districts:
        Area.objects.create(
            name=district['name'],
            center_point=Point(district['lng'], district['lat'], srid=4326)
        )


def reverse_populate(apps, schema_editor):
    """Rollback: 모든 Area 삭제"""
    Area = apps.get_model('grievances', 'Area')
    Area.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0004_grievancesecret_grievance_completed_at_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_seoul_areas, reverse_populate),
    ]
