# Generated by Django 5.0.1 on 2025-12-29 15:54

from django.db import migrations
from django.contrib.gis.geos import Point
from django.contrib.gis.db.models.functions import Distance


def populate_grievance_areas(apps, schema_editor):
    """
    기존 민원의 area 필드를 location CharField와 좌표 기반으로 채움
    """
    Grievance = apps.get_model('grievances', 'Grievance')
    Area = apps.get_model('grievances', 'Area')

    # Get default area for fallback
    default_area = Area.objects.get(name='미지정')

    # Build location name to area mapping
    area_map = {}
    for area in Area.objects.exclude(name='미지정'):
        # Match various formats: "강남구", "서울 강남구", "서울특별시 강남구" etc
        area_map[area.name] = area
        area_map[f"서울 {area.name}"] = area
        area_map[f"서울특별시 {area.name}"] = area

    for grievance in Grievance.objects.all():
        matched_area = None

        # Strategy 1: Match location CharField
        if grievance.location:
            for location_key, area in area_map.items():
                if location_key in grievance.location:
                    matched_area = area
                    break

        # Strategy 2: Find nearest area by center_point using PostGIS
        if not matched_area and grievance.point:
            nearest_area = Area.objects.exclude(name='미지정').annotate(
                distance=Distance('center_point', grievance.point)
            ).order_by('distance').first()

            if nearest_area:
                matched_area = nearest_area

        # Strategy 3: Fallback to default
        if not matched_area:
            matched_area = default_area

        grievance.area = matched_area
        grievance.save(update_fields=['area'])


def reverse_populate(apps, schema_editor):
    """Rollback: Set all area FKs to NULL"""
    Grievance = apps.get_model('grievances', 'Grievance')
    Grievance.objects.update(area=None)


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0005_populate_seoul_areas'),
    ]

    operations = [
        migrations.RunPython(populate_grievance_areas, reverse_populate),
    ]
