# Generated by Django 5.0.1 on 2025-12-29 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0006_populate_grievance_areas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='이 지역을 담당하는 정치인 또는 관리자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_areas', to=settings.AUTH_USER_MODEL, verbose_name='담당자'),
        ),
    ]
